waypoints:
  sofa:
    x: 3.5
    y: -2.5
    theta: 0.0
  cocina:
    x: 8.0
    y: -3.0
    theta: 0.0
  principal:
    x: 10.0
    y: 6.0
    theta: 0.0
  almacen:
    x: 12.0
    y: -1.0
    theta: 0.0
  banyo:
    x: 5.0
    y: 6.0
    theta: 0.0
  secundaria:
    x: 1.0
    y: 5.0
    theta: 0.0
  inicio:
    x: 0.0
    y: 0.0
    theta: 0.0
